### ISSUE TITLE
Decimal type is being serialized as a string

### ISSUE THREAD

**Issue by Mitch528** [neuecc/Utf8Json#10]
```cs
public class Foo
{
	public decimal Bar { get; set; }
}

JsonSerializer.ToJsonString(new Foo { Bar = 1.23m }); //outputs { "Bar": "1.23" } - should be { "Bar": 1.23 }

JsonSerializer.Deserialize<Foo>("{\"Bar\":1.23}"); //throws JsonParsingException: expected:", actual:. at:8
```

**Comment by neuecc** [comment]
I thought of accuracy, intentionally made it as a string.
But, as you say, Number is good (even for compatibility with JSON.NET etc).

I've changed DecimalFormatter serialize as number.
But can deserialize both string and number format(so not break compatibility).

**Comment by neuecc** [comment]
I've uploda `v1.1.0` it includes this changes.

**Comment by Mitch528** [comment]
Alright, great! Thanks.
