### ISSUE TITLE
Deserialization json string return a null list instead of an empty list

### ISSUE THREAD

**Issue by jarukitppg** [neuecc/Utf8Json#11]
```csharp
public class SomeClass
{
    public SomeClass()
    {
        AnotherClass = new List<AnotherClass>();
    }

    public List<AnotherClass> AnotherClass { get; set; }
}
```
```csharp
public class AnotherClass
{
    public int Foo { get; set;}
}
```
```csharp
string jsonString = "[{}]"

List<SomeClass> _list = new List<SomeClass>();

_list = JsonSerializer.Deserialize<List<SomeClass>>(jsonString);
```

The list of another class inside _list object equal to null, not an empty list.

**Comment by neuecc** [comment]
thank you, it occurs from overwrites default value always.
I've fixed when constructor has side-effect, check if member was read,
if use empty constructor, does not check member was read, so keep the performance.

**Comment by neuecc** [comment]
I've upload `v1.1.2` it includes this fix.

**Comment by jarukitppg** [comment]
Thank you for your response, it seems to fix now.
