### ISSUE TITLE
Error handle

### ISSUE THREAD

**Issue by tom123123123** [neuecc/Utf8Json#16]
hi, I like this lib very much, real fast indeed, and prepare replace json.net for my new project.
I wonder if Uft8Json can let me know which property or field failed when deserialize.
for example. 
a class contains Id property, int type, user provides wrong value "abc", must throw exception with additional fail reason (like ErrorEventArgs in json.net, through errorArg.ErrorContext.Path)

**Comment by neuecc** [comment]
Thank you for your suggestion.
Yes, currently error information is very poor.
I'll do
Phase 1, JsonParsingException has more kind information.
Phase 2, can handle(through next token, etc...) on event

```csharp
public class MyClass
{
    public int Id { get; set; }
}
```

```csharp
var json = "{\"Id\":\"abc\"}";

// Newtonsoft.Json.JsonReaderException: Could not convert string to integer: abc. Path 'Id', line 1, position 11.
// JsonReaderException can retrieve 'LineNumber', 'LinePosition', 'Path'.
//var a = Newtonsoft.Json.JsonConvert.DeserializeObject<MyClass>(json);

// Utf8Json.JsonParsingException: expected:,, actual:" at:6
// Oh, this is very very poor information...
var b = Utf8Json.JsonSerializer.Deserialize<MyClass>(json);
```

**Comment by neuecc** [comment]
I've released `Ver 1.2.1`, it shows more friendly info.

```csharp
var json = "{\"Id\":\"abc\"}";

// Utf8Json.JsonParsingException: expected:'Number Token', actual:'abc', at offset:6
var b = Utf8Json.JsonSerializer.Deserialize<MyClass>(json);
```

and can retrieve more info from JsonParsingException

```csharp
var json = "{\"Id\":\"abc\"}";

try
{
    var stream = new MemoryStream(Encoding.UTF8.GetBytes(json));
    var b = Utf8Json.JsonSerializer.Deserialize<MyClass>(stream);
}
catch (JsonParsingException ex)
{
    // expected:'Number Token', actual:'abc', at offset:6
    // JSON: {"Id":"abc"...
    Console.WriteLine(ex.Message); // ex.ActualChar, ex.Offset, ex.GetUnderlyingByteArrayUnsafe, ex.GetUnderlyingStringUnsafe
    Console.WriteLine("JSON: " + ex.GetUnderlyingStringUnsafe());
}
```

**Comment by tom123123123** [comment]
yes, it shows more friendly.
thanks, I'll close this one.

**Comment by investagrams** [comment]
Is there a way to handle the error and prevent from explicitly throwing a exception just like in newtonsoft? This way, the other fields can still deserialize and log the "Field" on which the error occured. Just like this one:


Newtonsoft.Json.JsonSerializer jsonSerializer = new Newtonsoft.Json.JsonSerializer();

                EventHandler<Newtonsoft.Json.Serialization.ErrorEventArgs> errorHandler = null;
                if (formatterLogger != null)
                {
                    // Error must always be marked as handled
                    // Failure to do so can cause the exception to be rethrown at every recursive level and overflow the stack for x64 CLR processes
                    errorHandler = (sender, e) =>
                    {
                        Exception exception = e.ErrorContext.Error;
                        formatterLogger.LogError(e.ErrorContext.Path, exception);
                        e.ErrorContext.Handled = true;
                    };
                    jsonSerializer.Error += errorHandler;
                }

                try
                {
                    var result = jsonSerializer.Deserialize(jsonReader, type);

                    return result;
                }
                finally
                {
                    if (errorHandler != null)
                    {
                        // Clean up the error handler in case CreateJsonSerializer() reuses a serializer
                        jsonSerializer.Error -= errorHandler;
                    }
                }

It is handling the error inside the json serializer
