### ISSUE TITLE
Is this still actual with .NET Core 3.0 release?

### ISSUE THREAD

**Issue by Svetomechc** [neuecc/Utf8Json#166]
https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#fast-built-in-json-support

**Comment by alexb5dh** [comment]
Some related benchmarks: https://michaelscodingspot.com/the-battle-of-c-to-json-serializers-in-net-core-3/

**Comment by Svetomechc** [comment]
@alexb5dh thanks! It was a surprise for me that Utf8Json outperforms the new System.Text.Json serializer, I had initially thought they would be close performance-wise. If only there were an official Utf8Json integration for ASP.NET Core 3.0 projects, having to write your own formatters is cumbersome.

**Comment by Svetomechc** [comment]
I will close this as related discussion seems to have moved to #170
