### ISSUE TITLE
Support for "$type"

### ISSUE THREAD

**Issue by Omnia-Code** [neuecc/Utf8Json#18]
Is there a way to support something like "$type"?
This would allow the following scenario:
```

    public class A { }

    public class B :A{ }

    public class C : A { }

public void Method()
{
         var list = new List<A>
            {
                new B(),
                new C()
            };
            var bytes = Utf8Json.JsonSerializer.Serialize(list);
            var dList = Utf8Json.JsonSerializer.Deserialize<List<A>>(bytes);

}

```

**Comment by neuecc** [comment]
Currently no.
I recommend if you want to use Typeless feature, use [MessagePack for C#](https://github.com/neuecc/MessagePack-CSharp/).
Here is the reason.
https://github.com/neuecc/Utf8Json#which-serializer-should-be-used

**Comment by Omnia-Code** [comment]
@neuecc Thanks a lot, I will try with MssagePack.
