### ISSUE TITLE
Is it possible to serialize long member as string?

### ISSUE THREAD

**Issue by AachoLoya** [neuecc/Utf8Json#248]
I have c# models with ID field defined as a long. Need to serialize the data into json, but since JavaScript doesn't support 64-bit values, I need to serialize only ID field as string, but in c# model keep it as long.

public class Profile
{
public long ID;
public string name;
public long userData;
}

Anyway to mark the ID field so its serialized as string? Hoping there is an attribute that I can use.

**Comment by AachoLoya** [comment]
Does anyone know?

**Comment by tomsoftware** [comment]
May you could try to proxy your value for Json using a getter / setter

```
    public class Test
    {
        [IgnoreDataMember]
        public long Id { get; set; }

        [DataMember(Name = "Id")]
        public string IdAsString
        {
            get
            {
                return Id.ToString();
            }

            set
            {
                this.Id = long.Parse(value);
            }
        }
    }
```

**Comment by AachoLoya** [comment]
I think that's the best way to go about doing this.
