### ISSUE TITLE
why only AggressiveInlining in NETSTANDARD?

### ISSUE THREAD

**Issue by SimonCropp** [neuecc/Utf8Json#26]
why is this only in NETSTANDARD?
```
#if NETSTANDARD
        [MethodImpl(AggressiveInlining)]
#endif
```

**Comment by neuecc** [comment]
NET45 is defined `NETSTANDARD` so does not need to worry about NETSTANDARD.
https://github.com/neuecc/Utf8Json/blob/master/src/Utf8Json/Utf8Json.csproj#L13

This symbols is for Unity(Unity's .NET Framework is .NET 3.5).

**Comment by SimonCropp** [comment]
ok thanks

**Comment by SimonCropp** [comment]
just an fyi this makes the codebase very hard to understand for anyone attempting a PR
