### ISSUE TITLE
Exception while deserializing with non-memorystreams

### ISSUE THREAD

**Issue by Tornhoof** [neuecc/Utf8Json#4]
Typed Deserialization without memorystreams does not work:

https://github.com/neuecc/Utf8Json/blob/2efcbd7d6e554acf3cf8d246448adba59489695d/src/Utf8Json/JsonSerializer.cs#L171-L177

You never check if ms is not null after your ``as``, so this will always break for non memorystreams

**Comment by neuecc** [comment]
oh, too bad code...

**Comment by neuecc** [comment]
thanks, released `1.0.1`.

**Comment by Tornhoof** [comment]
Works for me now. I'll close this one.
