### ISSUE TITLE
Class inheritance not supported in deserialization?

### ISSUE THREAD

**Issue by LordDevil1980** [neuecc/Utf8Json#43]
Hey there :)

I was trying to switch over from Json.NET to your utf8Json.

But I found out that it does not support inheritance of classes?

Example:
```
public abstract class JsonDBItem
    {
        public int ID { get { return _id; } }
        private int _id = -1;
    }

   public class Card: JsonDBItem
    {
        public string Name { get { return name; } }
        private string name = 0;
    }
```

Json:
"_id": 1,
"name": "DummyName"

I have AllowPrivate set to true - so the Json file will deserialize the name, but not the properties from the inherited class JsonDBItem -> ID is still empty - in Json.NET this worked. Any chance to make this possible in utf8json?

Thanks alot,
Oliver

**Comment by neuecc** [comment]
thanks, this is related to https://github.com/neuecc/MessagePack-CSharp/pull/174
currently does not search base type's private member.
I'll fix it.

**Comment by neuecc** [comment]
I've uploaded `1.3.7` that includes this fix, please try it.

**Comment by odysoftware** [comment]
Oh thats great thanks so much neuecc !! Now I should be able to switch over from old Json.net library to yours 👍

**Comment by LordDevil1980** [comment]
Thanks so much!! Now I can finally switch over to your library from Json.NET 👍

**Comment by TylerAP** [comment]
I have v1.3.7 and I have this issue with interface inheritance, the inherited interface has properties that don't get serialized...
I'm using Moq to create a mocked ISomeInterface that inherits from IBaseInterface, then calling JsonSerializer.NonGeneric.Serialize(typeof(ISomeInterface), obj) ... it only serializes ISomeInterface's properties, not IBaseInterface's.

**Comment by TylerAP** [comment]
I'll create a separate issue for this, I see the problem in the commit that adds this for 1.3.7; you're checking BaseType but not interfaces for public properties...

**Comment by TylerAP** [comment]
Linked to https://github.com/neuecc/Utf8Json/issues/81
