### ISSUE TITLE
Having MessagePack and UTF8Json in one project - causes lots of ambiguity issues.

### ISSUE THREAD

**Issue by odysoftware** [neuecc/Utf8Json#46]
Hey there,

I just saw when using UTF8Json and MessagePack in a unity project from your unitypackages - then you have a ambiguity between the Reflection.cs files of both projects - they share the same function - so you get several errors.

I am trying now to fix this myself - but just wanted to let you know.

**Comment by odysoftware** [comment]
Oh I just see that those 2 projects can't be used together in one project - because they share a lot of code which causes a lot of errors and warnings. Is there an easy fix to isolate those 2 projects from each other?

**Comment by neuecc** [comment]
most simplest way, create dll to separate assembly.
If you can use Unity 2017.3, Assembly Definition Files helps it easily.

I know some reflection shims causes there problem(firebase plugin and so on).

**Comment by odysoftware** [comment]
My problem is that I am using a GameData dll outside of unity - this is compiled against .net 3.5 - so I can't add your utf8json as a package to it - because of framework incompatilibty. Now I need to add the source code of utf8json to compile it, but this is causing the ambiguity errors - since I am also having the messagepack dll in.

But I'll see how I can sort this out, so thanks for the quick headsup 👍

**Comment by odysoftware** [comment]
BTW how can I make a Unity DLL out of your unitypackage Utf8Json? Its compiiled against .net standard 2 - but i think i can't use this dll in unity directly?

**Comment by neuecc** [comment]
unpack by Unity and put to .NET 3.5 project, and build it.

**Comment by odysoftware** [comment]
Now I feel stupid ;) Thanks!

**Comment by hiradyazdan** [comment]
@neuecc Is there any better way than what you suggested above? having both libraries in separate assemblies using assembly definitions sounds excessive. It would be nice if they were both wrapped in their specific namespaces or made as partials may be to avoid any conflicts.

**Comment by AArnott** [comment]
> For example System.Reflection namespace is quite a generic namespace as part of a third party library, why not use the library namespace instead so can isolate extension methods within the scope of the library itself?

This makes a lot of sense, IMO. The new MessagePack v2 doesn't contribute types to the System.Reflection namespace, FWIW.
