### ISSUE TITLE
AllowPrivate gets ignored in Unity?

### ISSUE THREAD

**Issue by odysoftware** [neuecc/Utf8Json#48]
I finally migrated everything to Utf8Json. So far it went smooth, but there seems to be an issue with the AllowPrivate Deserialisation in Unity. (using 2017.3.0f3).

```
JsonSerializer.SetDefaultResolver(Utf8Json.Resolvers.StandardResolver.AllowPrivate);
   TextAsset database = assetBundleMap.LoadAsset<TextAsset>("zones");
   jsonDB.Zones = JsonSerializer.Deserialize<JsonDB>(database.text).Zones; 
```
This is the complete same code which I am using server side via a .net Standard 2.0 dll of your Utf8Json.

But in Unity (using no AOT - I am building for Mac Universal for now) the private fields are all ignored - its the same classes I also use on the server - sharing same gamedata dll.

I tried to check if public fields work (to be sure I am not doing anything wrong) and as soon as I Deserialise public fields its working fine - but the AllowPrivate is completely ignored.

Any idea - because right now I am stuck and can't build the client again - since it doesnt get any data from my json files :). Must be some kind of issues with reflection in unity.

Thanks a lot,
Oliver

**Comment by odysoftware** [comment]
In the meantime I tried to create a GeneratedResolver with your UniversalCodeGeneration Tool on my classes - but it also only generates public fields/properties - is there a way to tell the code generation tool to create private fields?

**Comment by neuecc** [comment]
Thanks, allowprivate does not work correctly on Unity, I've fixed and released 1.3.7.1 on releases page.

code generator can not access to private field.
Because, as you can see, it is completely plain C# source code.

**Comment by odysoftware** [comment]
I see so with private fields I am stuck then on AOT devices?

**Comment by neuecc** [comment]
No.

**Comment by odysoftware** [comment]
Sorry, not sure what you mean with no? I am not stuck?

But what can I do then on iOS devices if I can't generate the resolver for private fields?

Thanks for your time,
Oliver

**Comment by odysoftware** [comment]
So I guess in order to work with Utf8Json & Unity - I will have to use public properties instead of private?
Since the code generator can't resolve private fields/props - what is then the use case for the AllowPrivate resolver? So in unity you will always need code generation for AOT Environments so why have an AllowPrivate resolve at all?

Thanks for clearing this up,
Oliver

**Comment by neuecc** [comment]
> Utf8Json & Unity - I will have to use public properties instead of private?

Yes, normally C# cannot access the private field.
But reflection can access to private but it is too slow.
AllowPrivateResolver uses LCG(lightweight codegen https://blogs.msdn.microsoft.com/joelpob/2004/03/31/hello-world-lcg-lightweight-code-gen-style/)
it can skip accessibility check with keeping performance.
But it can not use in AOT environment.

AllowPrivate resolver is normaly used in standard .net environemnt or only for PC Unity.

**Comment by neuecc** [comment]
I can make reflection based AllowPrivateResolver that works on AOT environments.
But my focus is performance and does not allowed slow option
so I don't create reflection based resolver.

**Comment by odysoftware** [comment]
Thanks alot for the detailed explanation. Now that makes sense. So Json.NET is going the slow reflection route and thats why it is working there - it even doesn't require any code generation for AOT - but thats why its a lot slower.

One more question that bothers me though with deserialization:
   ```
public class XY
{
public int ID { get { return _id; } }
private int _id = -1;
}
```
I just tried to deserialize now with my public property (which is readonly - no setter) and it strangely works. Can you explain me why this "ID" is deserialising even though there is no constructor for it?

With your messagepack for example - it was always asking for a valid constructor - but Utf8Json doesn't do this?

Thanks a lot for your time - its much appreciated.
Kind regards,
Oliver

**Comment by neuecc** [comment]
I don't know what do you want to say...
Please include reproducable sample code.

Utf8Json generates better code than MessagePack for C#, 
it can handle asymmetric(serialize-deserialize) better and if does not found constructor, uses [FormatterServices.GetUninitializedObject](https://msdn.microsoft.com/en-us/library/system.runtime.serialization.formatterservices.getuninitializedobject(v=vs.110).aspx).

**Comment by odysoftware** [comment]
Ah okay I guess thats what I mean.

So Utf8Json can deserialize without a constructor through GetUninitalizedObject - but MessagePack can't?

I was just curious why the above class deserialisation worked in utf8json but not in messagepack :)
