### ISSUE TITLE
Serialization with type name handling.

### ISSUE THREAD

**Issue by vkrasovskiy-playq** [neuecc/Utf8Json#50]
How can i get the same behavior, like in Json.Net with following code
```
new JsonSerializerSettings
{
    TypeNameHandling = TypeNameHandling.All
};
```
It so so helpful in situations like this:
```
public class A
{
    public B Base;
}

public class B 
{
}

public class C
{
}
...
var a = new A();
a.B = new C();
var str = Serialize(a);
a = Deserialize(str);

// expected typeof(C) but was typeofB()
Assert.AreEquals(a.B.GetType(), typeof(C))

```

Any suggestions?

**Comment by neuecc** [comment]
not supporting TypeNameHandling.All.
I've mentioned about it, I recommend to use MessagePack for C#'s Typeless.
https://github.com/neuecc/Utf8Json#which-serializer-should-be-used

**Comment by vkrasovskiy-playq** [comment]
@neuecc can I use Typeless functionality for Unity project?

**Comment by vkrasovskiy-playq** [comment]
I see, that MessagePackSerializer.Typeless commented by #NETSTANDARD define in Unity package project

**Comment by neuecc** [comment]
Yes, Typeless requires reflection/dynamic code gen so does not support.
