### ISSUE TITLE
Utf8Json.AspNetCoreMvcFormatter as default serializer sample

### ISSUE THREAD

**Issue by timdoke** [neuecc/Utf8Json#51]
To use Utf8Json.AspNetCoreMvcFormatter as the default serializer for all controller actions in a .net standard / core project, is anything required other than installing it?  I had to do a lot of things in my .net 4.6 project to have the Utf8Json become the default serializer..

I would sort of expect we need to register / unregister things in the startup code etc..

**Comment by neuecc** [comment]
MessagePack for C# that simliar architecture as Utf8Json,
That article will be a reference for customization.

https://www.strathweb.com/2017/06/using-messagepack-with-asp-net-core-mvc/
https://github.com/WebApiContrib/WebAPIContrib.Core/tree/master/src/WebApiContrib.Core.Formatter.MessagePack

**Comment by timdoke** [comment]
Perfect.. I'll try it out.  Thanks!

**Comment by azrinsani** [comment]
Hi, appreciate a simple example on how to configure the ut8json input formatters for ASP.Net core.

`public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers(). //What do I add here?`
