### ISSUE TITLE
Target .NET 4.0 Framework

### ISSUE THREAD

**Issue by mauricio-morales** [neuecc/Utf8Json#72]
Before diving deep into your code, is there a reason why you wouldn't support targeting .NET 4.0 framework?

**Comment by neuecc** [comment]
I think it can.
At first, I decided to support only .NET Standard so it is .NET 4.5.

**Comment by damianh** [comment]
.NET 4.0 support ended in Jan 2016.

**Comment by mauricio-morales** [comment]
Thanks @damianh, yeah, wish all orgs would move away from unsupported frameworks. At any rate, my need for it has been mitigated so I'm happy with `Utf8Json` only supporting 4.5+.

**Comment by damianh** [comment]
I'm of the opinion that OSS projects have no obligation to support orgs that use obsolete versions of things, unless they are sponsoring or paying in some way. But that's just like my opinion man 😄

**Comment by mauricio-morales** [comment]
I'm on board 😄. My intention was to find out if this was an intentional exclusion before we invested our time in. Since our need is gone, so is my drive to (agreed) waste my time supporting an obsolete framework.
