### ISSUE TITLE
Operation is not supported on this platform. Xamarin Forms iOS

### ISSUE THREAD

**Issue by kevinvella** [neuecc/Utf8Json#74]
Hi,

I was trying the PureSocketCluster library. Internally it uses Utf8Json. When i run it on iOS it gives me an Operation is not supported on this platform.

Running it on Xamarin.Android it works very well.

Versions:
Utf8Json - v1.3.7
Xamarin Forms - v2.5.1.444934

Hope this can help
Attaching some screenshots of the stack trace
![screen shot 2018-04-27 at 10 40 16](https://user-images.githubusercontent.com/15779395/39353232-5ca3c810-4a07-11e8-89f6-9d1d6e4d5756.png)
![screen shot 2018-04-27 at 10 40 09](https://user-images.githubusercontent.com/15779395/39353233-5cc3ce26-4a07-11e8-99d2-fa00b5e1f9e0.png)
![screen shot 2018-04-27 at 10 40 02](https://user-images.githubusercontent.com/15779395/39353234-5ce3535e-4a07-11e8-8418-5cebd70f219e.png)
![screen shot 2018-04-27 at 10 39 55](https://user-images.githubusercontent.com/15779395/39353235-5cffc6d8-4a07-11e8-88e1-235cf24c947e.png)
![screen shot 2018-04-27 at 10 39 48](https://user-images.githubusercontent.com/15779395/39353236-5d1e1bc4-4a07-11e8-9c89-c764d565f90b.png)
![screen shot 2018-04-27 at 10 39 41](https://user-images.githubusercontent.com/15779395/39353237-5d3eb82a-4a07-11e8-84fa-9bc23fa2d2f0.png)
![screen shot 2018-04-27 at 10 39 35](https://user-images.githubusercontent.com/15779395/39353238-5d62fb40-4a07-11e8-971a-1c613913a0ad.png)

**Comment by neuecc** [comment]
for iOS, required precode generation.
see: https://github.com/neuecc/Utf8Json#pre-code-generationunityxamarin-supports

**Comment by kevinvella** [comment]
@neuecc Ok. One question. How should i generate the resolvers for PureSocketCluster?

**Comment by neuecc** [comment]
related to https://github.com/Coinigy/PureSocketCluster/issues/8 ?
It seems to serialize `Dictionary<string, object>`.
https://github.com/Coinigy/PureSocketCluster/blob/master/src/PureSocketCluster/PureSocketClusterSocket.cs

I think configure and use include `PrimitiveObjectFormatter`, maybe works.

**Comment by kevinvella** [comment]
Yes i created an issue on their repo.

I am trying to get the universal code generator to work / figuring it out.

For the PrimitiveObjectFormatter, you saying something like this?

```
Utf8Json.Resolvers.CompositeResolver.RegisterAndSetAsDefault(
      // use generated resolver first, and combine many other generated/custom resolvers
      Utf8Json.Resolvers.DynamicCompositeResolver.Create(
            new Utf8Json.IJsonFormatter[] { PrimitiveObjectFormatter.Default  }
            ,new Utf8Json.IJsonFormatterResolver[] { Utf8Json.Resolvers.StandardResolver.Default }
      )
);
```

**Comment by kevinvella** [comment]
If i use
` Utf8Json.Resolvers.CompositeResolver.RegisterAndSetAsDefault(new Utf8Json.IJsonFormatter[] { PrimitiveObjectFormatter.Default });`

I get this
![screen shot 2018-04-27 at 13 53 15](https://user-images.githubusercontent.com/15779395/39361331-4474ac9e-4a22-11e8-84d1-e2aa8b72e91f.png)

**Comment by neuecc** [comment]
You can set like following.

```csharp
Utf8Json.Resolvers.CompositeResolver.RegisterAndSetAsDefault(
    new [] { PrimitiveObjectFormatter.Default },
    new [] { Utf8Json.Resolvers.StandardResolver.Default }
);
```

**Comment by kevinvella** [comment]
Using the above i get the same platform not support exception.

The type initializer for 'Utf8Json.Resolvers.Internal.DynamicObjectResolverAllowPrivateFalseExcludeNullFalseNameMutateOriginal' threw an exception.

Will continue trying to work out the universal code generator

**Comment by neuecc** [comment]
How about this?

```csharp
Utf8Json.Resolvers.CompositeResolver.RegisterAndSetAsDefault(
    new [] { PrimitiveObjectFormatter.Default },
    new Utf8Json.IJsonFormatterResolver[] 
    {
        // + code generator resolver(serialize custom type)

        Utf8Json.Resolvers.BuiltinResolver.Instance,
        // EnumResolver.Default,(can't serialize enum...)
        Utf8Json.Resolvers.DynamicGenericResolver.Instance,
        Utf8Json.Resolvers.AttributeFormatterResolver.Instance
    }
);
```

**Comment by ByronAP** [comment]
beat me to it

**Comment by ByronAP** [comment]
I will externalize the deserializer interface to allow modifications

**Comment by kevinvella** [comment]
Hoy cow. This works! :D :D

Receiving data from the websocket. Will try to send data shortly.

Thanks very much for this!!!
I'm in your debt hahaha
