### ISSUE TITLE
Missing hyphen '-' character in deserialized string

### ISSUE THREAD

**Issue by Lanayx** [neuecc/Utf8Json#9]
I used JsonSerializer.Deserialize method to deserialize an object. One field containing the value 

> "\u0428\u0440\u0438-\u041b\u0430\u043d\u043a\u0430"

 was deserialized to "ШриЛанка", i.e. hyphen was skipped.

**Comment by Lanayx** [comment]
Actually, found that this happends, not only with hyphen, for example "\u041d\u043e\u0432\u0430\u044f \u0437\u0435\u043b\u0430\u043d\u0434\u0438\u044f" was deserialized to "Новаязеландия", i.e. space was skipped.

**Comment by neuecc** [comment]
thank you, this is bug, when mixed unicode encoding with ascii, ignored ascii.
I've fixed and released update `v1.0.6`.

**Comment by Lanayx** [comment]
Thanks, I confirm the fix
